<?php
/**
 * User: jayinton
 * Date: 2019-08-09
 * Time: 18:31
 */

namespace Translate\Controller;


use Common\Controller\AdminBase;

class DemoController extends AdminBase
{
    protected $lang = 'zh';

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        if (!empty($_SERVER['Lang'])) {
            $this->lang = $_SERVER['Lang'];
        }
    }

    /**
     * 语言切换示例
     */
    function lang_switch()
    {
        $this->display();
    }
}